language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_script: 
  - composer self-update && composer update
script: 
  - vendor/bin/codecept build && vendor/bin/codecept run
  - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "xdebug.enable = On" >> /etc/hhvm/php.ini'
  - vendor/bin/codecept run --coverage --coverage-xml ../../build/logs/clover.xml
  - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "xdebug.enable = Off" >> /etc/hhvm/php.ini'
after_script:
  - CODECLIMATE_REPO_TOKEN="6f443d6d70f0ebf987eea38654854c1c89e228bba92616800c4a06f254eda183" ./vendor/bin/test-reporter
  - php vendor/bin/coveralls -v --coverage_clover=build/logs/clover.xml
branches:
  only:
    - master
    - dev
addons:
    code_climate:
        repo_token: 6f443d6d70f0ebf987eea38654854c1c89e228bba92616800c4a06f254eda183